version: "3"

services:
  consul:
    image: consul
    command: agent -server -ui -node=server-main -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  test-node:
    image: test-node
    environment:
      - RUST_LOG=client=debug
      - CONSUL_ADDR=consul
    scale: 5
    depends_on:
      - consul
      - test-supervisor
    cap_add:
      - NET_ADMIN
  test-supervisor:
    image: test-supervisor
    depends_on:
      - consul
    environment:
      - RUST_LOG=supervisor=debug,partition-sim=debug
      - CONSUL_ADDR=consul
    volumes:
      - supervisor:/app
    cap_add:
      - NET_ADMIN

volumes:
  supervisor:
